### ISSUE TITLE
unable to upgrade 2.8.9 to 2.92

### ISSUE THREAD

**Issue by Alpha-Dan** [netbox-community/netbox-docker#330] opened 2020-08-31 08:20 UTC
## Current Behavior

On my server :

docker-compose pull
docker-compose up -d
...

## Expected Behavior

On web interface I'm also in 2.8.9
...

## Debug Information

I don't have abnormal messages in my logs

result of docker-compose pull:

Pulling postgres (postgres:11-alpine)...
Trying to pull repository docker.io/library/postgres ...
11-alpine: Pulling from docker.io/library/postgres
Digest: sha256:0f4c894ec349429dd1533bd1af340e0b48396ee9b43f5d48908fe2b6c44bee1b
Status: Image is up to date for docker.io/postgres:11-alpine
Pulling redis (redis:5-alpine)...
Trying to pull repository docker.io/library/redis ...
5-alpine: Pulling from docker.io/library/redis
df20fa9351a1: Already exists
9b8c029ceab5: Already exists
e983a1eb737a: Already exists
660ad543c5fc: Pull complete
823cbe4f5025: Pull complete
e3dd0c30e1c8: Pull complete
Digest: sha256:6972ee00fd35854dd2925904e23cb047faa004df27c62cba842248c7db6bd99d
Status: Downloaded newer image for docker.io/redis:5-alpine
Pulling netbox-worker (netboxcommunity/netbox:latest)...
Trying to pull repository docker.io/netboxcommunity/netbox ...
latest: Pulling from docker.io/netboxcommunity/netbox
Digest: sha256:9dbeafa1e9f06ac8a5e550caff0827354e96de22916c4052ad3dea0739d75f1c
Status: Image is up to date for docker.io/netboxcommunity/netbox:latest
Pulling redis-cache (redis:5-alpine)...
Trying to pull repository docker.io/library/redis ...
5-alpine: Pulling from docker.io/library/redis
Digest: sha256:b011c1ca7fa97ed92d6c5995e5dd752dc37fe157c1b60ce96a6e35701851dabc
Status: Image is up to date for docker.io/redis:5-alpine
Pulling netbox (netboxcommunity/netbox:latest-ldap)...
Trying to pull repository docker.io/netboxcommunity/netbox ...
latest-ldap: Pulling from docker.io/netboxcommunity/netbox
Digest: sha256:2cbcadb79f51186e943628cda69cf97ae5c1cc15b8aedaa782de36b30f024537
Status: Image is up to date for docker.io/netboxcommunity/netbox:latest-ldap
Pulling nginx (nginx:1.17-alpine)...
Trying to pull repository docker.io/library/nginx ...
1.17-alpine: Pulling from docker.io/library/nginx
Digest: sha256:763e7f0188e378fef0c761854552c70bbd817555dc4de029681a2e972e25e30e
Status: Image is up to date for docker.io/nginx:1.17-alpine

**Comment by tobiasge** [comment] 2020-08-31 08:32
Duplicate of #325

**Closed as completed by tobiasge** 2020-08-31 08:32 UTC
