### ISSUE TITLE
Unable to configure LDAP authorizations.

### ISSUE THREAD

**Issue by BegBlev** [netbox-community/netbox-docker#690] opened 2022-01-21 08:23 UTC
### Current Behavior

I am unable to configure my Netbox container to get basic authorizations (is_active, is_staff and is_superuser) from LDAP (FreeIPA) groups .

I already configured a Netbox VM (v2.10.10) to do this and it works perfectly. But unfortunately, it does not work with my v2.11.12 container.
The container is an unmodified "netboxcommunity/netbox:v2.11.12-ldap" container from Docker Hub. The configuration is done through environment variables.

If I don't configure group search then authentication works. The configuration is then:
```
REMOTE_AUTH_ENABLED="true"
REMOTE_AUTH_BACKEND="netbox.authentication.LDAPBackend"
AUTH_LDAP_SERVER_URI="ldap://freeipa.domain.test"
REMOTE_AUTH_CREATE_USER="true"
AUTH_LDAP_BIND_AS_AUTHENTICATING_USER="true"
AUTH_LDAP_USER_DN_TEMPLATE="uid=%(user)s,cn=users,cn=accounts,dc=domain,dc=test"
LDAP_IGNORE_CERT_ERRORS="true"
```
If I configure group search then _authentication_ doesn't work (not able to login). The configuration is then:
```
REMOTE_AUTH_ENABLED="true"
REMOTE_AUTH_BACKEND="netbox.authentication.LDAPBackend"
AUTH_LDAP_SERVER_URI="ldap://freeipa.domain.test"
REMOTE_AUTH_CREATE_USER="true"
AUTH_LDAP_BIND_AS_AUTHENTICATING_USER="true"
AUTH_LDAP_USER_DN_TEMPLATE="uid=%(user)s,cn=users,cn=accounts,dc=domain,dc=test"
AUTH_LDAP_REQUIRE_GROUP_DN="cn=ipausers,cn=groups,cn=accounts,dc=domain,dc=test"
AUTH_LDAP_GROUP_SEARCH_BASEDN="cn=groups,cn=accounts,dc=domain,dc=test"
AUTH_LDAP_GROUP_SEARCH_CLASS="groupofnames"
AUTH_LDAP_FIND_GROUP_PERMS="true"
AUTH_LDAP_MIRROR_GROUPS="false"
AUTH_LDAP_IS_SUPERUSER_DN="cn=netbox-admins,cn=groups,cn=accounts,dc=domain,dc=test"
AUTH_LDAP_IS_ADMIN_DN="cn=netbox-admins,cn=groups,cn=accounts,dc=domain,dc=test"
LDAP_IGNORE_CERT_ERRORS="true"
```
I took some traces on LDAP (FreeIPA) server.
In the case it works (with the Netbox VM) I have these:
```
[root@idm ~]# tail -f /var/log/dirsrv/slapd-DOMAIN-TEST/access
[19/Jan/2022:11:37:19.892424161 -0500] conn=3044415 op=0 BIND dn="uid=bob,cn=users,cn=accounts,dc=domain,dc=test" method=128 version=3
[19/Jan/2022:11:37:19.917490798 -0500] conn=3044415 op=0 RESULT err=0 tag=97 nentries=0 wtime=0.000744266 optime=0.025087478 etime=0.025830115 dn="uid=bob,cn=users,cn=accounts,dc=domain,dc=test"
[19/Jan/2022:11:37:19.925543168 -0500] conn=3044415 op=1 SRCH base="uid=bob,cn=users,cn=accounts,dc=domain,dc=test" scope=0 filter="(objectClass=*)" attrs=ALL
[19/Jan/2022:11:37:19.927211939 -0500] conn=3044415 op=1 RESULT err=0 tag=101 nentries=1 wtime=0.000108758 optime=0.001682283 etime=0.001789117
[19/Jan/2022:11:37:19.928151971 -0500] conn=3044415 op=2 CMP dn="cn=ipausers,cn=groups,cn=accounts,dc=domain,dc=test" attr="member"
[19/Jan/2022:11:37:19.928509058 -0500] conn=3044415 op=2 RESULT err=6 tag=111 nentries=0 wtime=-9873692.799579442 optime=9873691.200866419 etime=0.000443996
[19/Jan/2022:11:37:19.929187533 -0500] conn=3044415 op=3 CMP dn="cn=netbox-admins,cn=groups,cn=accounts,dc=domain,dc=test" attr="member"
[19/Jan/2022:11:37:19.929444256 -0500] conn=3044415 op=3 RESULT err=6 tag=111 nentries=0 wtime=-9873692.798524298 optime=9873691.201801777 etime=0.000324313
[19/Jan/2022:11:37:19.929745639 -0500] conn=3044415 op=4 CMP dn="cn=netbox-admins,cn=groups,cn=accounts,dc=domain,dc=test" attr="member"
[19/Jan/2022:11:37:19.929950808 -0500] conn=3044415 op=4 RESULT err=6 tag=111 nentries=0 wtime=-9873692.797962939 optime=9873691.202308409 etime=0.000269750
```
Binding is done with login user (which is the expected behaviour) and then searches are done before unbinding.

In the case it does not work (with the Netbox container) I have these:
```
[root@freeipa cloud]# tail -f /var/log/dirsrv/slapd-DOMAIN-TEST/access
[19/Jan/2022:19:37:17.162526931 +0000] conn=834 fd=102 slot=102 connection from 172.16.0.98 to 192.168.201.29
[19/Jan/2022:19:37:17.162852163 +0000] conn=834 op=0 BIND dn="uid=bob,cn=users,cn=accounts,dc=domain,dc=test" method=128 version=3
[19/Jan/2022:19:37:17.236052843 +0000] conn=834 op=0 RESULT err=0 tag=97 nentries=0 etime=0.0073470336 dn="uid=bob,cn=users,cn=accounts,dc=domain,dc=test"
[19/Jan/2022:19:37:17.236942543 +0000] conn=834 op=1 BIND dn="" method=128 version=3
[19/Jan/2022:19:37:17.237098208 +0000] conn=834 op=1 RESULT err=0 tag=97 nentries=0 etime=0.0000222190 dn=""
[19/Jan/2022:19:37:17.240362484 +0000] conn=834 op=2 CMP dn="cn=ipausers,cn=groups,cn=accounts,dc=domain,dc=test" attr="member"
[19/Jan/2022:19:37:17.240538800 +0000] conn=834 op=2 RESULT err=50 tag=111 nentries=0 etime=0.0000233711
[19/Jan/2022:19:37:17.253773471 +0000] conn=834 op=3 UNBIND
[19/Jan/2022:19:37:17.253792563 +0000] conn=834 op=3 fd=102 closed - U1
```

Binding is done with login user for authentication (expected behaviour) but then there is a new bind with `dn=""` for group search.

### Expected Behavior

I Expect that when I login with a user active on my FreeIPA it works and the groups he belongs to (is_admin, is_staff) are reflected into Netbox.
If the user exists in FreeIPA but not in the Netbox DB then he is created in the DB.

This is the behavior I have on my Netbox VM

### Docker Compose Version

N/A (I use an unmodified "netboxcommunity/netbox:v2.11.12-ldap" container from Docker Hub)

### Docker Version

```text
My container is running on an Orange Flexible Engine K8S cluster.
Container Runtime Version:  docker://18.9.0
```

### The git Revision

v2.11.12

### The git Status

```text
N/A
```

### Startup Command

N/A

### NetBox Logs

```text
🧬 loaded config '/etc/netbox/config/configuration.py'
🧬 loaded config '/etc/netbox/config/extra.py'
🧬 loaded config '/etc/netbox/config/logging.py'
🧬 loaded config '/etc/netbox/config/plugins.py'
Operations to perform:
  Apply all migrations: admin, auth, circuits, contenttypes, dcim, extras, ipam, secrets, sessions, taggit, tenancy, users, virtualization
Running migrations:
  No migrations to apply.
🧬 loaded config '/etc/netbox/config/configuration.py'
🧬 loaded config '/etc/netbox/config/extra.py'
🧬 loaded config '/etc/netbox/config/logging.py'
🧬 loaded config '/etc/netbox/config/plugins.py'
💡 Superuser Username: admin, E-Mail: admin@example.com
🧬 loaded config '/etc/netbox/config/configuration.py'
🧬 loaded config '/etc/netbox/config/extra.py'
🧬 loaded config '/etc/netbox/config/logging.py'
🧬 loaded config '/etc/netbox/config/plugins.py'
▶️  Running the startup script /opt/netbox/startup_scripts/000_users.py
▶️  Running the startup script /opt/netbox/startup_scripts/010_groups.py
▶️  Running the startup script /opt/netbox/startup_scripts/015_object_permissions.py
▶️  Running the startup script /opt/netbox/startup_scripts/020_custom_fields.py
▶️  Running the startup script /opt/netbox/startup_scripts/020_tags.py
▶️  Running the startup script /opt/netbox/startup_scripts/030_regions.py
▶️  Running the startup script /opt/netbox/startup_scripts/040_sites.py
▶️  Running the startup script /opt/netbox/startup_scripts/050_manufacturers.py
▶️  Running the startup script /opt/netbox/startup_scripts/060_device_types.py
▶️  Running the startup script /opt/netbox/startup_scripts/070_rack_roles.py
▶️  Running the startup script /opt/netbox/startup_scripts/075_locations.py
▶️  Running the startup script /opt/netbox/startup_scripts/080_racks.py
▶️  Running the startup script /opt/netbox/startup_scripts/090_device_roles.py
▶️  Running the startup script /opt/netbox/startup_scripts/100_platforms.py
▶️  Running the startup script /opt/netbox/startup_scripts/110_tenant_groups.py
▶️  Running the startup script /opt/netbox/startup_scripts/120_tenants.py
▶️  Running the startup script /opt/netbox/startup_scripts/130_cluster_types.py
▶️  Running the startup script /opt/netbox/startup_scripts/135_cluster_groups.py
▶️  Running the startup script /opt/netbox/startup_scripts/135_clusters.py
▶️  Running the startup script /opt/netbox/startup_scripts/140_clusters.py
▶️  Running the startup script /opt/netbox/startup_scripts/140_devices.py
▶️  Running the startup script /opt/netbox/startup_scripts/150_rirs.py
▶️  Running the startup script /opt/netbox/startup_scripts/160_aggregates.py
▶️  Running the startup script /opt/netbox/startup_scripts/165_cluster_groups.py
▶️  Running the startup script /opt/netbox/startup_scripts/175_route_targets.py
▶️  Running the startup script /opt/netbox/startup_scripts/180_vrfs.py
▶️  Running the startup script /opt/netbox/startup_scripts/190_prefix_vlan_roles.py
▶️  Running the startup script /opt/netbox/startup_scripts/200_vlan_groups.py
▶️  Running the startup script /opt/netbox/startup_scripts/210_vlans.py
▶️  Running the startup script /opt/netbox/startup_scripts/220_prefixes.py
▶️  Running the startup script /opt/netbox/startup_scripts/230_virtual_machines.py
▶️  Running the startup script /opt/netbox/startup_scripts/240_virtualization_interfaces.py
▶️  Running the startup script /opt/netbox/startup_scripts/250_dcim_interfaces.py
▶️  Running the startup script /opt/netbox/startup_scripts/260_ip_addresses.py
▶️  Running the startup script /opt/netbox/startup_scripts/270_primary_ips.py
▶️  Running the startup script /opt/netbox/startup_scripts/280_custom_links.py
▶️  Running the startup script /opt/netbox/startup_scripts/280_providers.py
▶️  Running the startup script /opt/netbox/startup_scripts/290_circuit_types.py
▶️  Running the startup script /opt/netbox/startup_scripts/290_webhooks.py
▶️  Running the startup script /opt/netbox/startup_scripts/300_circuits.py
▶️  Running the startup script /opt/netbox/startup_scripts/310_secret_roles.py
▶️  Running the startup script /opt/netbox/startup_scripts/320_services.py
▶️  Running the startup script /opt/netbox/startup_scripts/330_power_panels.py
▶️  Running the startup script /opt/netbox/startup_scripts/340_power_feeds.py
✅ Initialisation is done.
⏳ Waiting for control socket to be created... (1/10)
2022/01/21 08:20:32 [info] 1#1 unit started
2022/01/21 08:20:32 [info] 17#17 discovery started
2022/01/21 08:20:32 [notice] 17#17 module: python 3.8.7 "/usr/lib/unit/modules/python3.unit.so"
2022/01/21 08:20:32 [info] 1#1 controller started
2022/01/21 08:20:32 [notice] 1#1 process 17 exited with code 0
2022/01/21 08:20:32 [info] 19#19 router started
2022/01/21 08:20:32 [info] 19#19 OpenSSL 1.1.1k  25 Mar 2021, 101010bf
⚙️ Applying configuration from /etc/unit/nginx-unit.json
2022/01/21 08:20:33 [info] 23#23 "netbox" application started
🧬 loaded config '/etc/netbox/config/configuration.py'
🧬 loaded config '/etc/netbox/config/extra.py'
🧬 loaded config '/etc/netbox/config/logging.py'
🧬 loaded config '/etc/netbox/config/plugins.py'
✅ Unit configuration loaded successfully
```

### Content of docker-compose.override.yml

```yaml
N/A... started with Terraform on a K8S cluster
All the connectivity (ports, services...) Docker stuff is nice as my container works when group authorizations are disabled.
```

**Comment by ryanmerolle** [comment] 2022-02-05 02:19
Duplicate of #689

**Closed as completed by ryanmerolle** 2022-02-05 02:19 UTC

**Comment by BegBlev** [comment] 2022-06-20 09:46
Hi,
I finally found the bug.
Actually, AUTH_LDAP_BIND_AS_AUTHENTICATING_USER is not read from environment. Hence, even if it is defined, Netbox will try to search for LDAP groups using AUTH_LDAP_BIND_DN/AUTH_LDAP_BIND_PASSWORD.

Could you please re-open the issue?
I will submit a merge request.

Thank you,
Vince
