### ISSUE TITLE
2.9.x configuration.py missing variables needed for LDAP

### ISSUE THREAD

**Issue by ziggekatten** [netbox-community/netbox-docker#335] opened 2020-09-02 06:13 UTC
## Current Behavior
Upgrade a 2.8.x to 2.9.2 disables LDAP login

...

## Expected Behavior
Upgrade from 2.8.x to 2.9.x should work with LDAP login. 

As of 2.9, there are additional parameters for authentication needed. For example, to get LDAP to work in 2.9 you need REMOTE_AUTH_ENABLED and REMOTE_AUTH_BACKEND defined, which was not needed in version 2.8

A refresh of the configuration.py is needed to include new variables/lists related to 2.9

...

**Comment by tobiasge** [comment] 2020-09-02 06:21
Duplicate of #324

**Closed as completed by tobiasge** 2020-09-02 06:21 UTC
