### ISSUE TITLE
Docker Hub build infra is broken / misses pip install step

### ISSUE THREAD

**Issue by sdktr** [netbox-community/netbox-docker#173] opened 2019-10-24 13:46 UTC
## Current Behavior

Pulled a fresh copy of a (previously working) v2.6.6 image. This image during startup complained about a missing drf_yasg module. Further research showed that the build log on Docker hub completely skips a step in the build proces. We never see a 'pip install .. requirements.txt'. 

## Expected Behavior

I expect the build in Docker Hub to include a build step for the netbox requirements
...

## Debug Information

https://hub.docker.com/layers/netboxcommunity/netbox/v2.6.6/images/sha256-69b75ca20af67085e6a4e0339f3b953f37fd64168b4147cb4d972a94b64f78b5
^^^ doesn't contain a pip install step

A working build (before multi-stage builds were introduced) have this in step 21:

> |2 BRANCH=v2.6.5 REQUIREMENTS_URL=https://raw.githubusercontent.com/netbox-community/netbox/v2.6.5/requirements.txt /bin/sh -c pip install -r requirements.txt

https://hub.docker.com/layers/netboxcommunity/netbox/v2.6.5/images/sha256-df1b48d0e455950e5cf9218466e6b526fffc7314cd6cc41cd93a3ceff8947c8c

**Comment by tobiasge** [comment] 2019-10-24 14:31
This is a duplicate of #170.
The requirements are installed in the builder image and the copied to the runtime image.

**Closed** 2019-10-24 14:33 UTC
Labels: duplicate
