### ISSUE TITLE
Serverr error when visitng "/dcim/sites/"  or "/dcim/devices/" after upgrading to 3.1.3

### ISSUE THREAD

**Issue by Mikeson** [netbox-community/netbox-docker#684] opened 2022-01-03 19:27 UTC
### Current Behavior

After upgrading to 3.1.3  from 3.0.9, it's impossible to display the sites : /dcim/sites/ or /dcim/devices/

The following message shows : 

<class 'django.template.exceptions.TemplateDoesNotExist'>

utilities/templatetags/tag.html

Python version: 3.9.5
NetBox version: 3.1.3

![chrome_Ujz6kGtz5E](https://user-images.githubusercontent.com/10764287/147971267-c1d2833a-e1ee-4d06-9f35-8a10e986efea.png)

I did a fresh install on another VM, I'm able to browse correctly fine, the issue apreas only after importing the data from a sql dump.

ls -l utilities/templatetags/ 
total 36
-rw-r--r--    1 root     root             0 Dec 30 05:51 __init__.py
-rw-r--r--    1 root     root          2308 Dec 30 05:51 buttons.py
-rw-r--r--    1 root     root          1395 Dec 30 05:51 form_helpers.py
-rw-r--r--    1 root     root         12371 Dec 30 05:51 helpers.py
-rw-r--r--    1 root     root           400 Dec 30 05:51 navigation.py
-rw-r--r--    1 root     root           664 Dec 30 05:51 perms.py
-rw-r--r--    1 root     root           318 Dec 30 05:51 search.py

### Expected Behavior

The sites and devices should be displayed. 

### Docker Compose Version

docker-compose version 1.23.2, build 1110ad01

### Docker Version

```text
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-208.git7d71120.el7_9.x86_64
 Go version:      go1.10.3
 Git commit:      7d71120/1.13.1
 Built:           Fri Jun  4 10:20:12 2021
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-208.git7d71120.el7_9.x86_64
 Go version:      go1.10.3
 Git commit:      7d71120/1.13.1
 Built:           Fri Jun  4 10:20:12 2021
 OS/Arch:         linux/amd64
 Experimental:    false
```

### The git Revision

58a157983259d3a9992776dbe9f166ca11d2f987

### The git Status

```text
On branch release
Your branch is up to date with 'origin/release'.

nothing to commit, working tree clean
```

### Startup Command

docker-compose up -d

### NetBox Logs

```text
Attaching to netbox-docker_netbox_1
netbox_1               | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox_1               | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox_1               | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox_1               | 🧬 loaded config '/etc/netbox/config/plugins.py'
netbox_1               | 💡 Superuser Username: admin, E-Mail: admin@example.com
netbox_1               | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox_1               | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox_1               | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox_1               | 🧬 loaded config '/etc/netbox/config/plugins.py'
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/000_users.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/010_groups.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/015_object_permissions.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/020_custom_fields.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/020_tags.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/020_tenant_groups.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/030_regions.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/030_tenants.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/040_sites.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/050_manufacturers.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/060_device_types.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/070_rack_roles.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/075_locations.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/080_racks.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/090_device_roles.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/100_platforms.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/130_cluster_types.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/135_cluster_groups.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/135_clusters.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/140_clusters.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/140_devices.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/150_rirs.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/160_aggregates.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/165_cluster_groups.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/175_route_targets.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/180_vrfs.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/190_prefix_vlan_roles.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/200_vlan_groups.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/210_vlans.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/220_prefixes.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/230_virtual_machines.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/240_virtualization_interfaces.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/250_dcim_interfaces.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/260_ip_addresses.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/270_primary_ips.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/280_custom_links.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/280_providers.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/290_circuit_types.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/290_webhooks.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/300_circuits.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/320_services.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/330_power_panels.py
netbox_1               | ▶️  Running the startup script /opt/netbox/startup_scripts/340_power_feeds.py
netbox_1               | ✅ Initialisation is done.
netbox_1               | ⏳ Waiting for control socket to be created... (1/10)
netbox_1               | 2022/01/03 19:17:43 [warn] 8#8 Unit is running unprivileged, then it cannot use arbitrary user and group.
netbox_1               | 2022/01/03 19:17:43 [info] 8#8 unit started
netbox_1               | 2022/01/03 19:17:43 [info] 17#17 discovery started
netbox_1               | 2022/01/03 19:17:43 [notice] 17#17 module: python 3.9.5 "/usr/lib/unit/modules/python3.unit.so"
netbox_1               | 2022/01/03 19:17:43 [info] 8#8 controller started
netbox_1               | 2022/01/03 19:17:43 [notice] 8#8 process 17 exited with code 0
netbox_1               | 2022/01/03 19:17:43 [info] 19#19 router started
netbox_1               | 2022/01/03 19:17:43 [info] 19#19 OpenSSL 1.1.1l  24 Aug 2021, 101010cf
netbox_1               | ⚙️ Applying configuration from /etc/unit/nginx-unit.json
netbox_1               | 2022/01/03 19:17:44 [info] 23#23 "netbox" application started
netbox_1               | ✅ Unit configuration loaded successfully
netbox_1               | 2022/01/03 19:17:46 [notice] 8#8 process 15 exited with code 0
```

### Content of docker-compose.override.yml

```yaml
version: '3.4'
services:
  netbox:
    ports:
      - 88:8080
```

**Comment by tobiasge** [comment] 2022-01-03 19:37
The problem is in Netbox 3.1.3 and not the Docker image. See this [bug report](https://github.com/netbox-community/netbox/issues/8187).
This was fixed in version 3.1.4 for which the images will be build with the next scheduled build.

**Closed as completed by tobiasge** 2022-01-03 19:37 UTC
