### ISSUE TITLE
Bug: Netbox Media Upload defect

### ISSUE THREAD

**Issue by Blackraz0r** [netbox-community/netbox-docker#283] opened 2020-05-05 13:15 UTC
## Steps to Reproduce

Fresh install via docker (compose file on a nfs mount)
try to upload picture. (for racks or for devices)

## Current Behavior

i tried to attach a picture to a rack or a device using the upload image function
it doesnt work
looks like this:
![81038640-030ba980-8ea7-11ea-8a9e-f2d7ba72e0ef 1](https://user-images.githubusercontent.com/26622216/81070071-0b81d580-8ee3-11ea-827b-2dbe731c65b7.jpg)

## Expected Behavior

i can upload the picture and attach it to the item

## Debug Information

The output of `docker-compose version`:
```docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019```

The output of `docker version`:
```Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e8ff056
 Built:             Thu Apr 11 04:43:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056
  Built:            Thu Apr 11 04:10:53 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

The output of `git rev-parse HEAD`:
```5769684c98efaa66049189793e66998b217c5ffa```

The command you used to start the project: ```docker-compose up -d```

The output of `docker inspect netboxcommunity/netbox:latest --format "{{json .Config.Labels}}"`:
```{"NETBOX_GIT_BRANCH":"HEAD","NETBOX_GIT_REF":"a77d1e502c07cd29bfd8e5074f4e8506fab42285","NETBOX_GIT_URL":"https://github.com/netbox-community/netbox.git","ORIGINAL_TAG":"docker.io/netboxcommunity/netbox:latest","org.label-schema.build-date":"2020-04-26T05:56+00:00","org.label-schema.description":"A container based distribution of Netbox, the free and open IPAM and DCIM solution.","org.label-schema.name":"Netbox Docker","org.label-schema.schema-version":"1.0","org.label-schema.url":"https://github.com/netbox-community/netbox-docker","org.label-schema.usage":"https://github.com/netbox-community/netbox-docker/wiki","org.label-schema.vcs-ref":"5769684c98efaa66049189793e66998b217c5ffa","org.label-schema.vcs-url":"https://github.com/netbox-community/netbox-docker.git","org.label-schema.vendor":"The netbox-docker contributors.","org.label-schema.version":"0.23.0","org.opencontainers.image.authors":"The netbox-docker contributors.","org.opencontainers.image.created":"2020-04-26T05:56+00:00","org.opencontainers.image.description":"A container based distribution of Netbox, the free and open IPAM and DCIM solution.","org.opencontainers.image.documentation":"https://github.com/netbox-community/netbox-docker/wiki","org.opencontainers.image.licenses":"Apache-2.0","org.opencontainers.image.revision":"5769684c98efaa66049189793e66998b217c5ffa","org.opencontainers.image.source":"https://github.com/netbox-community/netbox-docker.git","org.opencontainers.image.title":"Netbox Docker","org.opencontainers.image.url":"https://github.com/netbox-community/netbox-docker","org.opencontainers.image.vendor":"The netbox-docker contributors.","org.opencontainers.image.version":"0.23.0"}```

```json
{
  "JSON JSON JSON":
    "--> Please paste formatted json. (Use e.g. `jq` or https://jsonformatter.curiousconcept.com/)"
}
```

The output of `docker-compose logs netbox`:

https://gist.github.com/Blackraz0r/7cafcb8db8669629af1ebd9148168ee4

The output of `docker-compose logs nginx`:

https://gist.github.com/Blackraz0r/f168cc4fb2be0f9c2aba5d6dc56c3698

**Comment by weisdd** [comment] 2020-05-06 22:19
@Blackraz0r If you're using default docker-compose file, it should be the same issue as the one described here: https://github.com/netbox-community/netbox-docker/issues/252. There's already a fix merged into a "develop" branch (https://github.com/netbox-community/netbox-docker/pull/276). Thus, it should be fair to expect it in one of the upcoming releases, once the commit is cherry-picked into the "release" branch. Not sure when it'll happen though.

As it was discussed in #252, for now, you might want to manually change permissions for the media folder in your docker volume. You can find its actual location on the host machine in the output of "docker inspect <CONTAINER_ID>". E.g.:
```json
{
    "Type": "volume",
    "Name": "netbox-docker_netbox-media-files",
    "Source": "/var/lib/docker/volumes/netbox-docker_netbox-media-files/_data",
    "Destination": "/opt/netbox/netbox/media",
    "Driver": "local",
    "Mode": "z",
    "RW": true,
    "Propagation": ""
},
```
In this case, the fix would be:
```bash
$ sudo chmod -R g+w /var/lib/docker/volumes/netbox-docker_netbox-media-files/_data
```

If you plan to store the files somewhere else (like in a local folder), then you should do the same for the respective folder assuming its owner group is root.

**Comment by Blackraz0r** [comment] 2020-05-07 04:10
@weisdd 
Thank you for your help!
This solved it for me.
Glad to see its going to be fixed in some next future maybe.

Thank you mate!

**Comment by weisdd** [comment] 2020-05-07 09:19
@Blackraz0r I'm glad it helped :)

**Comment by cimnine** [comment] 2020-05-14 14:45
Duplicate of https://github.com/netbox-community/netbox-docker/issues/252

**Closed as completed by cimnine** 2020-05-14 14:45 UTC
Labels: duplicate, pr
