### ISSUE TITLE
Insufficient write permission to the media root in new v2.7.9 deployment

### ISSUE THREAD

**Issue by netgab** [netbox-community/netbox-docker#252] opened 2020-03-09 16:11 UTC
## Current Behavior

Installation of a new netbox-docker instance following the guides in the README.md and the wiki pages "Getting Started" and "Configuration".
The configuration env file was modified for production use.
In the netbox UI (no configuration until this point):
1.) Create a dummy "Manufacturer"
2.) Add a new device type using the dummy manufacturer as vendor and some dummy model description. Add a "front image" (jpg) and press "Create"

An error is displayed:

> Server Error
> A file permission error was detected while processing this request. Common causes include the following:
> Insufficient write permission to the media root - The configured media root is . Ensure that the user NetBox runs as has access to write files to all locations within this path.
> The complete exception is provided below:
> 
> <class 'PermissionError'>
> [Errno 13] Permission denied: '/opt/netbox/netbox/media/devicetype-images/image.jpg'
> 

...

## Expected Behavior

The new device type is created and the image is uploaded to netbox
...

## Debug Information

The output of `docker-compose version`: `docker-compose version 1.21.1, build 5a3f1a3`
The output of `docker version`: ` Version: 19.03.7`
The output of `git rev-parse HEAD`: `80f514fa90997bc7b132ea06b84056c6720f37d0`
The command you used to start the project: `docker-compose up -d`

The output of `docker inspect netboxcommunity/netbox:latest --format "{{json .Config.Labels}}"`:

```json
{"NETBOX_GIT_BRANCH":"HEAD","NETBOX_GIT_REF":"c1ef87e0097e550511725bf060f2527fbe91b9e2","NETBOX_GIT_URL":"https://github.com/netbox-community/netbox.git","ORIGINAL_TAG":"docker.io/netboxcommunity/netbox:latest","org.label-schema.build-date":"2020-03-08T05:58+00:00","org.label-schema.description":"A container based distribution of Netbox, the free and open IPAM and DCIM solution.","org.label-schema.name":"Netbox Docker","org.label-schema.schema-version":"1.0","org.label-schema.url":"https://github.com/netbox-community/netbox-docker","org.label-schema.usage":"https://github.com/netbox-community/netbox-docker/wiki","org.label-schema.vcs-ref":"80f514fa90997bc7b132ea06b84056c6720f37d0","org.label-schema.vcs-url":"https://github.com/netbox-community/netbox-docker.git","org.label-schema.vendor":"The netbox-docker contributors.","org.label-schema.version":"0.22.0","org.opencontainers.image.authors":"The netbox-docker contributors.","org.opencontainers.image.created":"2020-03-08T05:58+00:00","org.opencontainers.image.description":"A container based distribution of Netbox, the free and open IPAM and DCIM solution.","org.opencontainers.image.documentation":"https://github.com/netbox-community/netbox-docker/wiki","org.opencontainers.image.licenses":"Apache-2.0","org.opencontainers.image.revision":"80f514fa90997bc7b132ea06b84056c6720f37d0","org.opencontainers.image.source":"https://github.com/netbox-community/netbox-docker.git","org.opencontainers.image.title":"Netbox Docker","org.opencontainers.image.url":"https://github.com/netbox-community/netbox-docker","org.opencontainers.image.vendor":"The netbox-docker contributors.","org.opencontainers.image.version":"0.22.0"}
```

The output of `docker-compose logs netbox`:
(on "create" button press)
```text
netbox_1         | [2020-03-09 16:09:11 +0000] [26] [DEBUG] POST /dcim/device-types/add/
netbox_1         | 172.19.0.7 - - [09/Mar/2020:16:09:11 +0000] "POST /dcim/device-types/add/ HTTP/1.0" 500 2038 "https://netbox.********/dcim/device-types/add/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0"
```

**Comment by leemachine** [comment] 2020-03-10 17:19
I have confirmed this issue. It looks like the media directory is being mounted on the read-only volume and not the media volume.

```
docker exec -it netboxdocker_netbox_1 sh -c 'df /opt/netbox/netbox/media/'
Filesystem           1K-blocks      Used Available Use% Mounted on
/dev/mapper/root--vg-root--lv
                      78600708   6474728  72125980   8% /etc/netbox-nginx
```

**Comment by leemachine** [comment] 2020-03-10 19:08
A workaround for this issue is to chmod the volume data on the host.
`chmod -R 777 /var/lib/docker/volumes/netboxdocker_netbox-media-files/_data/`

After that device images can be saved/uploaded

**Comment by cimnine** [comment] 2020-03-15 15:59
Thank you for reporting this issue on Github.

Unfortunately I don't have time to look into it at the moment. It'd be great if anyone could suggest a permanent solution.

A different work-around to the one suggested above (which is limited to Linux) is to revert to running Netbox to run as default user, i.e. _root_. Add these lines to your `docker-compose.override.yml` file to achieve this:

```yml
version: '3.4'
services:
  netbox:
    user: null
  netbox-worker:
    user: null
```

**Comment by weisdd** [comment] 2020-04-18 14:33
@cimnine It requires a tiny change in Dockerfile:
```
RUN mkdir static && chmod g+w static media
```
->
```
RUN mkdir static && chmod -R g+w static media
```
Since chmod for the media folder was not recursive, g+w was not inherited by media subfolders. Thus, even users with gid 0 could not create files.

@leemachine Without the above-mentioned fix, I'd rather recommend g+w instead of 777 as a workaround. - It adds +w to root group, which any container user not present in /etc/passwd and /etc/group belongs to by default.

**Comment by cimnine** [comment] 2020-05-16 15:23
I believe this should be resolved in the next release, which is imminent. If it isn't, feel free to re-open the issue.

**Closed as completed by cimnine** 2020-05-16 15:23 UTC
Labels: bug, pr
